---
# ------------------------------------------------------------------------------
# Set up directory structure for software installation
# ------------------------------------------------------------------------------


- name:                 "Creating the Oracle Home and Oracle Base Directory"
  include_tasks:        add_new_install_dir.yml
  with_items:
    - /opt/app
    - /opt/app/12.1.0/grid
    - /opt/app/grid
    - /opt/app/oracle
  loop_control:
    loop_var:           install_dir
  tags:                 add_new_install_dir
...
