---
# ------------------------------------------------------------------------------
# Set up directory structure for software installation
# ------------------------------------------------------------------------------


- name:                 "Creating the Oracle Home and Oracle Base Directory"
  file:
    path:               "/opt/{{ item }}"
    owner:              oracle
    group:              "{{ oracle_user.install_group.name }}"
    state:              directory
  with_items:
    - app/12.1.0/grid
    - app/grid
    - app/oracle
...
