---
# ------------------------------------------------------------------------------
# Mount shared software location via NFS
# ------------------------------------------------------------------------------


- name:                 "Install NFS Utilities Software"
  yum:
    name:               nfs-utils
    state:              present
        
- name:                 "Create Mount Point for Oracle Installation Software"
  file:
    path:               "{{ software_nfs_loc }}"
    state:              directory

- name:                 "Mount NFS Share for Oracle Installation Software"
  mount:
    path:               "{{ software_nfs_loc }}"
    src:                narrabri.yaocm.id.au:/data/Software
    fstype:             nfs4
    opts:               ro,bg,hard,nointr,rsize=32768,wsize=32768,tcp,vers=4,timeo=600
    state:              mounted
...
