---
# ------------------------------------------------------------------------------
# Checks the cluster is ready for the installation of Grid Infrastructure (GI)
# ------------------------------------------------------------------------------

- name:                 "Checks the cluster is ready for the installation of Grid Infrastructure (GI)"
  block:
  
  - set_fact:
      installer_loc:    "{{ software_nfs_loc }}/grid/linuxamd64_12102/grid"

  - name:               "Run Verification Checks for CRS Installation"
    command:            "{{ installer_loc }}/runcluvfy.sh stage -pre crsinst -n {{ ansible_hostname }}"
    changed_when:       false
    failed_when:        false
    no_log:             true
    register:           cluvfy_status

  - debug:
      var:              cluvfy_status.stdout_lines
      verbosity:        0
    
  become:               yes
  become_user:          oracle
  when:                 first_node
  tags:                 crsinst_pre
...
