---
# ------------------------------------------------------------------------------
# Checks the cluster is ready for the installation of Grid Infrastructure (GI)
# ------------------------------------------------------------------------------

- name:                 "Checks the cluster is ready for the installation of Grid Infrastructure (GI)"
  block:

  - name:               "Run Verification Checks for CRS Installation"
    command:            "{{ oracle_gi.cluvfy_home }}/bin/cluvfy stage -pre crsinst -n {{ ansible_hostname }} -r 12.1"
    register:           cluvfy_status

  - debug:
      var:              cluvfy_status.stdout_lines
      verbosity:        0
    
  become:               yes
  become_user:          oracle
  when:                 first_node
  tags:                 crsinst_pre

# ------------------------------------------------------------------------------
# Configures cluster on first node only
# ------------------------------------------------------------------------------

- name:                 "Configure Cluster on first node only"
  block:

  - name:               "Set Facts for configuration of Cluster"
    set_fact:
      config_response_file:
                        "{{ oracle_gi.oracle_base }}/crs_config.rsp"
      config_loc:       "{{ oracle_gi.crs_home }}/crs/config"
      tool_response_file:    
                        "{{ oracle_gi.oracle_base }}/cfgrsp.properties"
      tool_loc:         "{{ oracle_gi.crs_home }}/cfgtoollogs"

  - name:               "Load Oracle User Password"
    include_vars:
      file:             oracle_pw.yml
      name:             oracle_file_pw

  - name:               "Create response file for silent CRS configuration"
    template:
      src:              "grid_install.rsp"
      dest:             "{{ config_response_file }}"
    vars:
      install_option:   "CRS_CONFIG"
      oracle_pw:
        SYSASMPassword: "{{ oracle_file_pw.SYSASMPassword }}"
        monitorPassword:
                        "{{ oracle_file_pw.monitorPassword }}"

  - name:               "Silently configure CRS on first node only"
    command:            "{{ config_loc }}/config.sh -silent -responseFile {{ config_response_file }} -waitforcompletion -ignorePrereq"
    args:
      chdir:            "{{ config_loc }}"
    register:           gi_config_result
  
  - debug:
      var:              gi_config_result.stdout_lines
      verbosity:        0

  - name:               "Run root.sh on first node"
    block:
    - name:             "Run root.sh on first node"
      command:          "{{ oracle_gi.crs_home }}/root.sh"
      register:         config_root_log

    - debug:
        var:            config_root_log.stdout_lines
        vebosity:       0
    when:
    - gi_config_result is succeeded
    - gi_config_result.changed
    become:             yes
    become_user:        root
      
  - name:               "Create response file for silent tools configuration"
    template:
      src:              "cfgrsp.properties"
      dest:             "{{ tool_response_file }}"
    vars:
      oracle_pw:
        SYSASMPassword: "{{ oracle_file_pw.SYSASMPassword }}"
        monitorPassword:
                        "{{ oracle_file_pw.monitorPassword }}"

  - name:               "Silently configure tools on first node only"
    command:            "{{ tool_loc }}/configToolAllCommands RESPONSE_FILE={{ tool_response_file }}"
    args:
      chdir:            "{{ tool_loc }}"
    register:           tool_config_result
  
  - debug:
      var:              tool_config_result.stdout_lines
      verbosity:        0
  when:                 first_node
  become:               yes
  become_user:          oracle
  tags:                 config_crs

...
