---
# tasks file for oracle_gi
# =============================================================================
# (0) Disable firewall
# (1) Install Oracle ASMLib Driver
# (2) Configure Oracle ASMLib Driver
# (3) Install Oracle GI 12.1.0.2 Software Only
# (4) Patch GI Home to PSU 20180116
# (5) Install CRS
# ==============================================================================

- name:		    Install and configure Oracle ASMLib driver
  block:
    - import_tasks: disable_firewall.yml
    - import_tasks: gi_asm.yml
    - import_tasks: oracleasm.yml
  become:           yes
  become_user:      root

- name:             Install Oracle GI 12.1.0.2 Software Only
  block:
    - import_tasks: install_gi_sw.yml
    - import_tasks: install_tfa.yml
    - import_tasks: apply_gi_psu.yml
      vars:
        patch_num:  '27468957'
        min_opatch_vers:
                    '12.1.0.1.7'
        curr_opatch_vers:
                    '122010'
      tags:         apply_psu
    - import_tasks: crs_inst.yml
      tags:         crs_inst
  become:           yes
  become_user:      oracle
  tags:             install_gi_sw
...
