---
# tasks file for oracle_gi
# =============================================================================
# (1) Install Oracle ASMLib Driver
# (2) Configure Oracle ASMLib Driver
# (3) Install Oracle GI 12.1.0.2 Software Only
# ==============================================================================

- name:		    Install and configure Oracle ASMLib driver
  block:
    - import_tasks: gi_asm.yml
    - import_tasks: oracleasm.yml
  become:           yes
  become_user:      root

- name:             Install Oracle GI 12.1.0.2 Software Only
  block:
    - import_tasks: install_gi_sw.yml
  become:           yes
  become_user:      oracle
  tags:             install_gi_sw
...
