---
# ============================================================================
# Ensure that the Oracle ASMLib driver is configured and enabled
#   User should be 'oracle'
#   Group should be 'asmadmin'
# ============================================================================

- name:         Get Oracle ASMLib Driver Configuration
  command:      /usr/sbin/oracleasm configure
  register:     oasm_config
  changed_when: false

- debug:
    var:        oasm_config
    verbosity:  1

- name:         Set Owner for Oracle ASMLib Driver
  command:      /usr/sbin/oracleasm configure -u oracle
  when:         oasm_config.stdout_lines[1] != "ORACLEASM_UID=oracle"

- name:         Set Group for Oracle ASMLib Driver
  command:      /usr/sbin/oracleasm configure -g asmadmin
  when:         oasm_config.stdout_lines[2] != "ORACLEASM_GID=asmadmin"

- name:         Enable Oracle ASMLib Driver
  command:      /usr/sbin/oracleasm configure -e
  when:         oasm_config.stdout_lines[0] == "ORACLEASM_ENABLED=false"

# ============================================================================
# Ensure that the Oracle ASMLib Driver is initialized and loaded
# ============================================================================

- name:         Check Oracle ASMLib Driver Status
  command:      /usr/sbin/oracleasm status
  register:     oasm_status
  changed_when: false
  failed_when:  false
  no_log:       true

- debug:
    var:         oasm_status
    verbosity:   1

- name:         Load and initialize Oracle ASMLib Driver
  command:      /usr/sbin/oracleasm init
  when:         oasm_status.stdout_lines[0] is match("Checking if ASM is loaded. no")

- name:         Verify Oracle ASMLib Driver is loaded and initialized
  command:      /usr/sbin/oracleasm status
  register:     oasm_status
  changed_when: false

# ============================================================================
# Initialize all required disk devices with the Oracle ASMLib driver
# ============================================================================
- include_tasks: oracleasm_init_disk.yml
  with_items:
  - { dev: /dev/xvdd, disk: DATA }
  - { dev: /dev/xvde, disk: FRA  }
  - { dev: /dev/xvdf, disk: REDO1 }
  - { dev: /dev/xvdg, disk: REDO2 }
  - { dev: /dev/xvdh, disk: VOTE }
  loop_control:
    loop_var:    oasm_disk
...
